//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.23 at 10:03:12 AM BST 
//


package ebay.apis.eblbasecomponents;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ebay.apis.eblbasecomponents package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ebay.apis.eblbasecomponents
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetSellerTransactionsResponse }
     * 
     */
    public GetSellerTransactionsResponse createGetSellerTransactionsResponse() {
        return new GetSellerTransactionsResponse();
    }

    /**
     * Create an instance of {@link GetSellerTransactionsResponse.TransactionArray }
     * 
     */
    public GetSellerTransactionsResponse.TransactionArray createGetSellerTransactionsResponseTransactionArray() {
        return new GetSellerTransactionsResponse.TransactionArray();
    }

    /**
     * Create an instance of {@link GetSellerTransactionsResponse.TransactionArray.Transaction }
     * 
     */
    public GetSellerTransactionsResponse.TransactionArray.Transaction createGetSellerTransactionsResponseTransactionArrayTransaction() {
        return new GetSellerTransactionsResponse.TransactionArray.Transaction();
    }

    /**
     * Create an instance of {@link GetSellerTransactionsResponse.TransactionArray.Transaction.Taxes }
     * 
     */
    public GetSellerTransactionsResponse.TransactionArray.Transaction.Taxes createGetSellerTransactionsResponseTransactionArrayTransactionTaxes() {
        return new GetSellerTransactionsResponse.TransactionArray.Transaction.Taxes();
    }

    /**
     * Create an instance of {@link GetSellerTransactionsResponse.TransactionArray.Transaction.Taxes.TaxDetails }
     * 
     */
    public GetSellerTransactionsResponse.TransactionArray.Transaction.Taxes.TaxDetails createGetSellerTransactionsResponseTransactionArrayTransactionTaxesTaxDetails() {
        return new GetSellerTransactionsResponse.TransactionArray.Transaction.Taxes.TaxDetails();
    }

    /**
     * Create an instance of {@link GetSellerTransactionsResponse.TransactionArray.Transaction.ShippingServiceSelected }
     * 
     */
    public GetSellerTransactionsResponse.TransactionArray.Transaction.ShippingServiceSelected createGetSellerTransactionsResponseTransactionArrayTransactionShippingServiceSelected() {
        return new GetSellerTransactionsResponse.TransactionArray.Transaction.ShippingServiceSelected();
    }

    /**
     * Create an instance of {@link GetSellerTransactionsResponse.TransactionArray.Transaction.Item }
     * 
     */
    public GetSellerTransactionsResponse.TransactionArray.Transaction.Item createGetSellerTransactionsResponseTransactionArrayTransactionItem() {
        return new GetSellerTransactionsResponse.TransactionArray.Transaction.Item();
    }

    /**
     * Create an instance of {@link GetSellerTransactionsResponse.TransactionArray.Transaction.Item.SellingStatus }
     * 
     */
    public GetSellerTransactionsResponse.TransactionArray.Transaction.Item.SellingStatus createGetSellerTransactionsResponseTransactionArrayTransactionItemSellingStatus() {
        return new GetSellerTransactionsResponse.TransactionArray.Transaction.Item.SellingStatus();
    }

    /**
     * Create an instance of {@link GetSellerTransactionsResponse.TransactionArray.Transaction.ShippingDetails }
     * 
     */
    public GetSellerTransactionsResponse.TransactionArray.Transaction.ShippingDetails createGetSellerTransactionsResponseTransactionArrayTransactionShippingDetails() {
        return new GetSellerTransactionsResponse.TransactionArray.Transaction.ShippingDetails();
    }

    /**
     * Create an instance of {@link GetSellerTransactionsResponse.TransactionArray.Transaction.Buyer }
     * 
     */
    public GetSellerTransactionsResponse.TransactionArray.Transaction.Buyer createGetSellerTransactionsResponseTransactionArrayTransactionBuyer() {
        return new GetSellerTransactionsResponse.TransactionArray.Transaction.Buyer();
    }

    /**
     * Create an instance of {@link GetSellerTransactionsResponse.TransactionArray.Transaction.Buyer.BuyerInfo }
     * 
     */
    public GetSellerTransactionsResponse.TransactionArray.Transaction.Buyer.BuyerInfo createGetSellerTransactionsResponseTransactionArrayTransactionBuyerBuyerInfo() {
        return new GetSellerTransactionsResponse.TransactionArray.Transaction.Buyer.BuyerInfo();
    }

    /**
     * Create an instance of {@link GetSellerTransactionsResponse.Seller }
     * 
     */
    public GetSellerTransactionsResponse.Seller createGetSellerTransactionsResponseSeller() {
        return new GetSellerTransactionsResponse.Seller();
    }

    /**
     * Create an instance of {@link GetSellerTransactionsResponse.PaginationResult }
     * 
     */
    public GetSellerTransactionsResponse.PaginationResult createGetSellerTransactionsResponsePaginationResult() {
        return new GetSellerTransactionsResponse.PaginationResult();
    }

    /**
     * Create an instance of {@link GetSellerTransactionsResponse.TransactionArray.Transaction.AmountPaid }
     * 
     */
    public GetSellerTransactionsResponse.TransactionArray.Transaction.AmountPaid createGetSellerTransactionsResponseTransactionArrayTransactionAmountPaid() {
        return new GetSellerTransactionsResponse.TransactionArray.Transaction.AmountPaid();
    }

    /**
     * Create an instance of {@link GetSellerTransactionsResponse.TransactionArray.Transaction.AdjustmentAmount }
     * 
     */
    public GetSellerTransactionsResponse.TransactionArray.Transaction.AdjustmentAmount createGetSellerTransactionsResponseTransactionArrayTransactionAdjustmentAmount() {
        return new GetSellerTransactionsResponse.TransactionArray.Transaction.AdjustmentAmount();
    }

    /**
     * Create an instance of {@link GetSellerTransactionsResponse.TransactionArray.Transaction.ConvertedAdjustmentAmount }
     * 
     */
    public GetSellerTransactionsResponse.TransactionArray.Transaction.ConvertedAdjustmentAmount createGetSellerTransactionsResponseTransactionArrayTransactionConvertedAdjustmentAmount() {
        return new GetSellerTransactionsResponse.TransactionArray.Transaction.ConvertedAdjustmentAmount();
    }

    /**
     * Create an instance of {@link GetSellerTransactionsResponse.TransactionArray.Transaction.ConvertedAmountPaid }
     * 
     */
    public GetSellerTransactionsResponse.TransactionArray.Transaction.ConvertedAmountPaid createGetSellerTransactionsResponseTransactionArrayTransactionConvertedAmountPaid() {
        return new GetSellerTransactionsResponse.TransactionArray.Transaction.ConvertedAmountPaid();
    }

    /**
     * Create an instance of {@link GetSellerTransactionsResponse.TransactionArray.Transaction.ConvertedTransactionPrice }
     * 
     */
    public GetSellerTransactionsResponse.TransactionArray.Transaction.ConvertedTransactionPrice createGetSellerTransactionsResponseTransactionArrayTransactionConvertedTransactionPrice() {
        return new GetSellerTransactionsResponse.TransactionArray.Transaction.ConvertedTransactionPrice();
    }

    /**
     * Create an instance of {@link GetSellerTransactionsResponse.TransactionArray.Transaction.Status }
     * 
     */
    public GetSellerTransactionsResponse.TransactionArray.Transaction.Status createGetSellerTransactionsResponseTransactionArrayTransactionStatus() {
        return new GetSellerTransactionsResponse.TransactionArray.Transaction.Status();
    }

    /**
     * Create an instance of {@link GetSellerTransactionsResponse.TransactionArray.Transaction.TransactionPrice }
     * 
     */
    public GetSellerTransactionsResponse.TransactionArray.Transaction.TransactionPrice createGetSellerTransactionsResponseTransactionArrayTransactionTransactionPrice() {
        return new GetSellerTransactionsResponse.TransactionArray.Transaction.TransactionPrice();
    }

    /**
     * Create an instance of {@link GetSellerTransactionsResponse.TransactionArray.Transaction.ActualShippingCost }
     * 
     */
    public GetSellerTransactionsResponse.TransactionArray.Transaction.ActualShippingCost createGetSellerTransactionsResponseTransactionArrayTransactionActualShippingCost() {
        return new GetSellerTransactionsResponse.TransactionArray.Transaction.ActualShippingCost();
    }

    /**
     * Create an instance of {@link GetSellerTransactionsResponse.TransactionArray.Transaction.ActualHandlingCost }
     * 
     */
    public GetSellerTransactionsResponse.TransactionArray.Transaction.ActualHandlingCost createGetSellerTransactionsResponseTransactionArrayTransactionActualHandlingCost() {
        return new GetSellerTransactionsResponse.TransactionArray.Transaction.ActualHandlingCost();
    }

    /**
     * Create an instance of {@link GetSellerTransactionsResponse.TransactionArray.Transaction.Taxes.TotalTaxAmount }
     * 
     */
    public GetSellerTransactionsResponse.TransactionArray.Transaction.Taxes.TotalTaxAmount createGetSellerTransactionsResponseTransactionArrayTransactionTaxesTotalTaxAmount() {
        return new GetSellerTransactionsResponse.TransactionArray.Transaction.Taxes.TotalTaxAmount();
    }

    /**
     * Create an instance of {@link GetSellerTransactionsResponse.TransactionArray.Transaction.Taxes.TaxDetails.TaxAmount }
     * 
     */
    public GetSellerTransactionsResponse.TransactionArray.Transaction.Taxes.TaxDetails.TaxAmount createGetSellerTransactionsResponseTransactionArrayTransactionTaxesTaxDetailsTaxAmount() {
        return new GetSellerTransactionsResponse.TransactionArray.Transaction.Taxes.TaxDetails.TaxAmount();
    }

    /**
     * Create an instance of {@link GetSellerTransactionsResponse.TransactionArray.Transaction.Taxes.TaxDetails.TaxOnSubtotalAmount }
     * 
     */
    public GetSellerTransactionsResponse.TransactionArray.Transaction.Taxes.TaxDetails.TaxOnSubtotalAmount createGetSellerTransactionsResponseTransactionArrayTransactionTaxesTaxDetailsTaxOnSubtotalAmount() {
        return new GetSellerTransactionsResponse.TransactionArray.Transaction.Taxes.TaxDetails.TaxOnSubtotalAmount();
    }

    /**
     * Create an instance of {@link GetSellerTransactionsResponse.TransactionArray.Transaction.Taxes.TaxDetails.TaxOnShippingAmount }
     * 
     */
    public GetSellerTransactionsResponse.TransactionArray.Transaction.Taxes.TaxDetails.TaxOnShippingAmount createGetSellerTransactionsResponseTransactionArrayTransactionTaxesTaxDetailsTaxOnShippingAmount() {
        return new GetSellerTransactionsResponse.TransactionArray.Transaction.Taxes.TaxDetails.TaxOnShippingAmount();
    }

    /**
     * Create an instance of {@link GetSellerTransactionsResponse.TransactionArray.Transaction.Taxes.TaxDetails.TaxOnHandlingAmount }
     * 
     */
    public GetSellerTransactionsResponse.TransactionArray.Transaction.Taxes.TaxDetails.TaxOnHandlingAmount createGetSellerTransactionsResponseTransactionArrayTransactionTaxesTaxDetailsTaxOnHandlingAmount() {
        return new GetSellerTransactionsResponse.TransactionArray.Transaction.Taxes.TaxDetails.TaxOnHandlingAmount();
    }

    /**
     * Create an instance of {@link GetSellerTransactionsResponse.TransactionArray.Transaction.ShippingServiceSelected.ShippingServiceCost }
     * 
     */
    public GetSellerTransactionsResponse.TransactionArray.Transaction.ShippingServiceSelected.ShippingServiceCost createGetSellerTransactionsResponseTransactionArrayTransactionShippingServiceSelectedShippingServiceCost() {
        return new GetSellerTransactionsResponse.TransactionArray.Transaction.ShippingServiceSelected.ShippingServiceCost();
    }

    /**
     * Create an instance of {@link GetSellerTransactionsResponse.TransactionArray.Transaction.ShippingServiceSelected.ShippingPackageInfo }
     * 
     */
    public GetSellerTransactionsResponse.TransactionArray.Transaction.ShippingServiceSelected.ShippingPackageInfo createGetSellerTransactionsResponseTransactionArrayTransactionShippingServiceSelectedShippingPackageInfo() {
        return new GetSellerTransactionsResponse.TransactionArray.Transaction.ShippingServiceSelected.ShippingPackageInfo();
    }

    /**
     * Create an instance of {@link GetSellerTransactionsResponse.TransactionArray.Transaction.Item.SellingStatus.CurrentPrice }
     * 
     */
    public GetSellerTransactionsResponse.TransactionArray.Transaction.Item.SellingStatus.CurrentPrice createGetSellerTransactionsResponseTransactionArrayTransactionItemSellingStatusCurrentPrice() {
        return new GetSellerTransactionsResponse.TransactionArray.Transaction.Item.SellingStatus.CurrentPrice();
    }

    /**
     * Create an instance of {@link GetSellerTransactionsResponse.TransactionArray.Transaction.ShippingDetails.SalesTax }
     * 
     */
    public GetSellerTransactionsResponse.TransactionArray.Transaction.ShippingDetails.SalesTax createGetSellerTransactionsResponseTransactionArrayTransactionShippingDetailsSalesTax() {
        return new GetSellerTransactionsResponse.TransactionArray.Transaction.ShippingDetails.SalesTax();
    }

    /**
     * Create an instance of {@link GetSellerTransactionsResponse.TransactionArray.Transaction.ShippingDetails.CODCost }
     * 
     */
    public GetSellerTransactionsResponse.TransactionArray.Transaction.ShippingDetails.CODCost createGetSellerTransactionsResponseTransactionArrayTransactionShippingDetailsCODCost() {
        return new GetSellerTransactionsResponse.TransactionArray.Transaction.ShippingDetails.CODCost();
    }

    /**
     * Create an instance of {@link GetSellerTransactionsResponse.TransactionArray.Transaction.Buyer.BuyerInfo.ShippingAddress }
     * 
     */
    public GetSellerTransactionsResponse.TransactionArray.Transaction.Buyer.BuyerInfo.ShippingAddress createGetSellerTransactionsResponseTransactionArrayTransactionBuyerBuyerInfoShippingAddress() {
        return new GetSellerTransactionsResponse.TransactionArray.Transaction.Buyer.BuyerInfo.ShippingAddress();
    }

    /**
     * Create an instance of {@link GetSellerTransactionsResponse.Seller.SellerInfo }
     * 
     */
    public GetSellerTransactionsResponse.Seller.SellerInfo createGetSellerTransactionsResponseSellerSellerInfo() {
        return new GetSellerTransactionsResponse.Seller.SellerInfo();
    }

}
