//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.23 at 10:03:12 AM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:ebay:apis:eBLBaseComponents", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ebay.apis.eblbasecomponents;
